let regularVerbs = [];
let irregularVerbs = [];

function loadVerbTables() {
    loadRegularVerbs();
    loadIrregularVerbs();
}

function loadRegularVerbs() {
    regularVerbs = [
        { title: "accept", base: "accept", past: "accepted", participle: "accepted", spanish: "aceptar", examples: ["I accept your offer", "She accepted the job"] },
        { title: "add", base: "add", past: "added", participle: "added", spanish: "añadir", examples: ["Add some salt", "He added sugar to his coffee"] },
        { title: "agree", base: "agree", past: "agreed", participle: "agreed", spanish: "estar de acuerdo", examples: ["I agree with you", "They agreed to help"] },
        { title: "allow", base: "allow", past: "allowed", participle: "allowed", spanish: "permitir", examples: ["Dogs are not allowed", "She allowed me to go"] },
        { title: "answer", base: "answer", past: "answered", participle: "answered", spanish: "responder", examples: ["Answer the question", "He answered quickly"] },
        { title: "appear", base: "appear", past: "appeared", participle: "appeared", spanish: "aparecer", examples: ["The sun appeared", "She appeared nervous"] },
        { title: "arrive", base: "arrive", past: "arrived", participle: "arrived", spanish: "llegar", examples: ["The train arrived late", "We arrived at 6 PM"] },
        { title: "ask", base: "ask", past: "asked", participle: "asked", spanish: "preguntar", examples: ["Ask a question", "She asked for help"] },
        { title: "believe", base: "believe", past: "believed", participle: "believed", spanish: "creer", examples: ["I believe you", "He believed the story"] },
        { title: "belong", base: "belong", past: "belonged", participle: "belonged", spanish: "pertenecer", examples: ["This belongs to me", "The book belonged to her"] },
        { title: "call", base: "call", past: "called", participle: "called", spanish: "llamar", examples: ["Call me later", "She called yesterday"] },
        { title: "carry", base: "carry", past: "carried", participle: "carried", spanish: "llevar", examples: ["Carry this bag", "He carried the boxes"] },
        { title: "change", base: "change", past: "changed", participle: "changed", spanish: "cambiar", examples: ["Change your clothes", "The weather changed"] },
        { title: "clean", base: "clean", past: "cleaned", participle: "cleaned", spanish: "limpiar", examples: ["Clean your room", "She cleaned the house"] },
        { title: "close", base: "close", past: "closed", participle: "closed", spanish: "cerrar", examples: ["Close the door", "The store closed early"] },
        { title: "cook", base: "cook", past: "cooked", participle: "cooked", spanish: "cocinar", examples: ["Cook dinner", "He cooked pasta"] },
        { title: "copy", base: "copy", past: "copied", participle: "copied", spanish: "copiar", examples: ["Copy this text", "She copied the homework"] },
        { title: "count", base: "count", past: "counted", participle: "counted", spanish: "contar", examples: ["Count to ten", "He counted the money"] },
        { title: "create", base: "create", past: "created", participle: "created", spanish: "crear", examples: ["Create a new file", "She created a masterpiece"] },
        { title: "dance", base: "dance", past: "danced", participle: "danced", spanish: "bailar", examples: ["Dance with me", "They danced all night"] },
        { title: "decide", base: "decide", past: "decided", participle: "decided", spanish: "decidir", examples: ["Decide quickly", "We decided to stay"] },
        { title: "describe", base: "describe", past: "described", participle: "described", spanish: "describir", examples: ["Describe the problem", "He described the scene"] },
        { title: "develop", base: "develop", past: "developed", participle: "developed", spanish: "desarrollar", examples: ["Develop new skills", "The company developed software"] },
        { title: "die", base: "die", past: "died", participle: "died", spanish: "morir", examples: ["The plant died", "He died peacefully"] },
        { title: "discover", base: "discover", past: "discovered", participle: "discovered", spanish: "descubrir", examples: ["Discover new places", "She discovered the truth"] },
        { title: "discuss", base: "discuss", past: "discussed", participle: "discussed", spanish: "discutir", examples: ["Discuss the plan", "We discussed the problem"] },
        { title: "dress", base: "dress", past: "dressed", participle: "dressed", spanish: "vestirse", examples: ["Dress warmly", "She dressed quickly"] },
        { title: "drop", base: "drop", past: "dropped", participle: "dropped", spanish: "dejar caer", examples: ["Don't drop it", "He dropped his keys"] },
        { title: "earn", base: "earn", past: "earned", participle: "earned", spanish: "ganar", examples: ["Earn money", "She earned a degree"] },
        { title: "end", base: "end", past: "ended", participle: "ended", spanish: "terminar", examples: ["The movie ended", "School ended at 3 PM"] },
        { title: "enjoy", base: "enjoy", past: "enjoyed", participle: "enjoyed", spanish: "disfrutar", examples: ["Enjoy your meal", "We enjoyed the party"] },
        { title: "enter", base: "enter", past: "entered", participle: "entered", spanish: "entrar", examples: ["Enter the room", "He entered the building"] },
        { title: "escape", base: "escape", past: "escaped", participle: "escaped", spanish: "escapar", examples: ["Escape from danger", "The prisoner escaped"] },
        { title: "exist", base: "exist", past: "existed", participle: "existed", spanish: "existir", examples: ["Does it exist?", "Dinosaurs existed long ago"] },
        { title: "explain", base: "explain", past: "explained", participle: "explained", spanish: "explicar", examples: ["Explain the rule", "She explained clearly"] },
        { title: "fail", base: "fail", past: "failed", participle: "failed", spanish: "fallar", examples: ["Don't fail the test", "The plan failed"] },
        { title: "fill", base: "fill", past: "filled", participle: "filled", spanish: "llenar", examples: ["Fill the glass", "The room filled with smoke"] },
        { title: "finish", base: "finish", past: "finished", participle: "finished", spanish: "terminar", examples: ["Finish your work", "We finished early"] },
        { title: "follow", base: "follow", past: "followed", participle: "followed", spanish: "seguir", examples: ["Follow me", "The dog followed us"] },
        { title: "form", base: "form", past: "formed", participle: "formed", spanish: "formar", examples: ["Form a line", "Clouds formed in the sky"] },
        { title: "guess", base: "guess", past: "guessed", participle: "guessed", spanish: "adivinar", examples: ["Guess the answer", "I guessed correctly"] },
        { title: "happen", base: "happen", past: "happened", participle: "happened", spanish: "suceder", examples: ["What happened?", "The accident happened yesterday"] },
        { title: "help", base: "help", past: "helped", participle: "helped", spanish: "ayudar", examples: ["Help me please", "She helped her friend"] },
        { title: "hope", base: "hope", past: "hoped", participle: "hoped", spanish: "esperar", examples: ["I hope so", "We hoped for good weather"] },
        { title: "hurry", base: "hurry", past: "hurried", participle: "hurried", spanish: "apresurarse", examples: ["Hurry up!", "She hurried to work"] },
        { title: "include", base: "include", past: "included", participle: "included", spanish: "incluir", examples: ["Include everyone", "The price included tax"] },
        { title: "increase", base: "increase", past: "increased", participle: "increased", spanish: "aumentar", examples: ["Increase the volume", "Prices increased"] },
        { title: "invite", base: "invite", past: "invited", participle: "invited", spanish: "invitar", examples: ["Invite your friends", "She invited me to dinner"] },
        { title: "join", base: "join", past: "joined", participle: "joined", spanish: "unirse", examples: ["Join the club", "He joined the army"] },
        { title: "jump", base: "jump", past: "jumped", participle: "jumped", spanish: "saltar", examples: ["Jump high", "The cat jumped on the table"] },
        { title: "kill", base: "kill", past: "killed", participle: "killed", spanish: "matar", examples: ["Don't kill insects", "The frost killed the plants"] },
        { title: "knock", base: "knock", past: "knocked", participle: "knocked", spanish: "golpear", examples: ["Knock on the door", "Someone knocked loudly"] },
        { title: "land", base: "land", past: "landed", participle: "landed", spanish: "aterrizar", examples: ["The plane landed", "We landed safely"] }
    ];
}

function loadIrregularVerbs() {
    irregularVerbs = [
        { title: "be", base: "be", past: "was/were", participle: "been", spanish: "ser/estar", examples: ["I am happy", "She was tired yesterday"] },
        { title: "have", base: "have", past: "had", participle: "had", spanish: "tener", examples: ["I have a car", "He had lunch at noon"] },
        { title: "do", base: "do", past: "did", participle: "done", spanish: "hacer", examples: ["Do your homework", "She did it well"] },
        { title: "say", base: "say", past: "said", participle: "said", spanish: "decir", examples: ["Say hello", "He said goodbye"] },
        { title: "get", base: "get", past: "got", participle: "got/gotten", spanish: "obtener", examples: ["Get the book", "I got a present"] },
        { title: "make", base: "make", past: "made", participle: "made", spanish: "hacer", examples: ["Make dinner", "She made a cake"] },
        { title: "go", base: "go", past: "went", participle: "gone", spanish: "ir", examples: ["Go home", "They went to Paris"] },
        { title: "know", base: "know", past: "knew", participle: "known", spanish: "saber/conocer", examples: ["I know you", "She knew the answer"] },
        { title: "take", base: "take", past: "took", participle: "taken", spanish: "tomar", examples: ["Take this", "He took the bus"] },
        { title: "see", base: "see", past: "saw", participle: "seen", spanish: "ver", examples: ["See you later", "I saw a movie"] },
        { title: "come", base: "come", past: "came", participle: "come", spanish: "venir", examples: ["Come here", "She came early"] },
        { title: "think", base: "think", past: "thought", participle: "thought", spanish: "pensar", examples: ["Think about it", "I thought of you"] },
        { title: "look", base: "look", past: "looked", participle: "looked", spanish: "mirar", examples: ["Look at me", "She looked tired"] },
        { title: "want", base: "want", past: "wanted", participle: "wanted", spanish: "querer", examples: ["I want coffee", "He wanted to go"] },
        { title: "give", base: "give", past: "gave", participle: "given", spanish: "dar", examples: ["Give me that", "She gave a gift"] },
        { title: "use", base: "use", past: "used", participle: "used", spanish: "usar", examples: ["Use this pen", "He used the computer"] },
        { title: "find", base: "find", past: "found", participle: "found", spanish: "encontrar", examples: ["Find your keys", "I found it!"] },
        { title: "tell", base: "tell", past: "told", participle: "told", spanish: "decir/contar", examples: ["Tell me", "She told a story"] },
        { title: "work", base: "work", past: "worked", participle: "worked", spanish: "trabajar", examples: ["Work hard", "She worked late"] },
        { title: "seem", base: "seem", past: "seemed", participle: "seemed", spanish: "parecer", examples: ["You seem tired", "It seemed easy"] },
        { title: "feel", base: "feel", past: "felt", participle: "felt", spanish: "sentir", examples: ["Feel better", "I felt sad"] },
        { title: "try", base: "try", past: "tried", participle: "tried", spanish: "intentar", examples: ["Try again", "She tried hard"] },
        { title: "leave", base: "leave", past: "left", participle: "left", spanish: "dejar/salir", examples: ["Leave now", "He left early"] },
        { title: "call", base: "call", past: "called", participle: "called", spanish: "llamar", examples: ["Call me", "She called yesterday"] },
        { title: "put", base: "put", past: "put", participle: "put", spanish: "poner", examples: ["Put it here", "He put on his coat"] },
        { title: "mean", base: "mean", past: "meant", participle: "meant", spanish: "significar", examples: ["What does it mean?", "I meant to call"] },
        { title: "keep", base: "keep", past: "kept", participle: "kept", spanish: "mantener", examples: ["Keep quiet", "She kept the secret"] },
        { title: "let", base: "let", past: "let", participle: "let", spanish: "dejar/permitir", examples: ["Let me go", "They let us in"] },
        { title: "begin", base: "begin", past: "began", participle: "begun", spanish: "empezar", examples: ["Begin now", "The movie began"] },
        { title: "show", base: "show", past: "showed", participle: "shown", spanish: "mostrar", examples: ["Show me", "He showed the way"] },
        { title: "hear", base: "hear", past: "heard", participle: "heard", spanish: "oír", examples: ["Hear the music", "I heard a noise"] },
        { title: "play", base: "play", past: "played", participle: "played", spanish: "jugar", examples: ["Play football", "They played well"] },
        { title: "run", base: "run", past: "ran", participle: "run", spanish: "correr", examples: ["Run fast", "She ran home"] },
        { title: "move", base: "move", past: "moved", participle: "moved", spanish: "mover", examples: ["Move the chair", "We moved house"] },
        { title: "live", base: "live", past: "lived", participle: "lived", spanish: "vivir", examples: ["Live here", "He lived in Spain"] },
        { title: "bring", base: "bring", past: "brought", participle: "brought", spanish: "traer", examples: ["Bring your book", "He brought flowers"] },
        { title: "write", base: "write", past: "wrote", participle: "written", spanish: "escribir", examples: ["Write a letter", "She wrote a book"] },
        { title: "sit", base: "sit", past: "sat", participle: "sat", spanish: "sentarse", examples: ["Sit down", "He sat quietly"] },
        { title: "stand", base: "stand", past: "stood", participle: "stood", spanish: "estar de pie", examples: ["Stand up", "She stood by the door"] },
        { title: "lose", base: "lose", past: "lost", participle: "lost", spanish: "perder", examples: ["Don't lose it", "I lost my keys"] },
        { title: "pay", base: "pay", past: "paid", participle: "paid", spanish: "pagar", examples: ["Pay the bill", "She paid cash"] },
        { title: "meet", base: "meet", past: "met", participle: "met", spanish: "conocer/encontrar", examples: ["Meet me there", "We met yesterday"] },
        { title: "set", base: "set", past: "set", participle: "set", spanish: "poner/establecer", examples: ["Set the table", "He set a record"] },
        { title: "learn", base: "learn", past: "learned/learnt", participle: "learned/learnt", spanish: "aprender", examples: ["Learn English", "She learned quickly"] }
    ];
}
