let regularVerbs = [];
let irregularVerbs = [];

function loadVerbTables() {
    loadRegularVerbs();
    loadIrregularVerbs();
}

function loadRegularVerbs() {
    regularVerbs = [
        { title: "accept", base: "accept", past: "accepted", participle: "accepted", spanish: "aceptar", examples: ["I accept your offer", "She accepted the job"] },
        { title: "add", base: "add", past: "added", participle: "added", spanish: "añadir", examples: ["Add some salt", "He added sugar to his coffee"] },
        { title: "agree", base: "agree", past: "agreed", participle: "agreed", spanish: "estar de acuerdo", examples: ["I agree with you", "They agreed to help"] },
        { title: "allow", base: "allow", past: "allowed", participle: "allowed", spanish: "permitir", examples: ["Dogs are not allowed", "She allowed me to go"] },
        { title: "answer", base: "answer", past: "answered", participle: "answered", spanish: "responder", examples: ["Answer the question", "He answered quickly"] },
        { title: "appear", base: "appear", past: "appeared", participle: "appeared", spanish: "aparecer", examples: ["The sun appeared", "She appeared nervous"] },
        { title: "arrive", base: "arrive", past: "arrived", participle: "arrived", spanish: "llegar", examples: ["The train arrived late", "We arrived at 6 PM"] },
        { title: "ask", base: "ask", past: "asked", participle: "asked", spanish: "preguntar", examples: ["Ask a question", "She asked for help"] },
        { title: "believe", base: "believe", past: "believed", participle: "believed", spanish: "creer", examples: ["I believe you", "He believed the story"] },
        { title: "belong", base: "belong", past: "belonged", participle: "belonged", spanish: "pertenecer", examples: ["This belongs to me", "The book belonged to her"] },
        { title: "call", base: "call", past: "called", participle: "called", spanish: "llamar", examples: ["Call me later", "She called yesterday"] },
        { title: "carry", base: "carry", past: "carried", participle: "carried", spanish: "llevar", examples: ["Carry this bag", "He carried the boxes"] },
        { title: "change", base: "change", past: "changed", participle: "changed", spanish: "cambiar", examples: ["Change your clothes", "The weather changed"] },
        { title: "clean", base: "clean", past: "cleaned", participle: "cleaned", spanish: "limpiar", examples: ["Clean your room", "She cleaned the house"] },
        { title: "close", base: "close", past: "closed", participle: "closed", spanish: "cerrar", examples: ["Close the door", "The store closed early"] },
        { title: "cook", base: "cook", past: "cooked", participle: "cooked", spanish: "cocinar", examples: ["Cook dinner", "He cooked pasta"] },
        { title: "copy", base: "copy", past: "copied", participle: "copied", spanish: "copiar", examples: ["Copy this text", "She copied the homework"] },
        { title: "count", base: "count", past: "counted", participle: "counted", spanish: "contar", examples: ["Count to ten", "He counted the money"] },
        { title: "create", base: "create", past: "created", participle: "created", spanish: "crear", examples: ["Create a new file", "She created a masterpiece"] },
        { title: "dance", base: "dance", past: "danced", participle: "danced", spanish: "bailar", examples: ["Dance with me", "They danced all night"] },
        { title: "decide", base: "decide", past: "decided", participle: "decided", spanish: "decidir", examples: ["Decide quickly", "We decided to stay"] },
        { title: "describe", base: "describe", past: "described", participle: "described", spanish: "describir", examples: ["Describe the problem", "He described the scene"] },
        { title: "develop", base: "develop", past: "developed", participle: "developed", spanish: "desarrollar", examples: ["Develop new skills", "The company developed software"] },
        { title: "die", base: "die", past: "died", participle: "died", spanish: "morir", examples: ["The plant died", "He died peacefully"] },
        { title: "discover", base: "discover", past: "discovered", participle: "discovered", spanish: "descubrir", examples: ["Discover new places", "She discovered the truth"] },
        { title: "discuss", base: "discuss", past: "discussed", participle: "discussed", spanish: "discutir", examples: ["Discuss the plan", "We discussed the problem"] },
        { title: "dress", base: "dress", past: "dressed", participle: "dressed", spanish: "vestirse", examples: ["Dress warmly", "She dressed quickly"] },
        { title: "drop", base: "drop", past: "dropped", participle: "dropped", spanish: "dejar caer", examples: ["Don't drop it", "He dropped his keys"] },
        { title: "earn", base: "earn", past: "earned", participle: "earned", spanish: "ganar", examples: ["Earn money", "She earned a degree"] },
        { title: "end", base: "end", past: "ended", participle: "ended", spanish: "terminar", examples: ["The movie ended", "School ended at 3 PM"] },
        { title: "enjoy", base: "enjoy", past: "enjoyed", participle: "enjoyed", spanish: "disfrutar", examples: ["Enjoy your meal", "We enjoyed the party"] },
        { title: "enter", base: "enter", past: "entered", participle: "entered", spanish: "entrar", examples: ["Enter the room", "He entered the building"] },
        { title: "escape", base: "escape", past: "escaped", participle: "escaped", spanish: "escapar", examples: ["Escape from danger", "The prisoner escaped"] },
        { title: "exist", base: "exist", past: "existed", participle: "existed", spanish: "existir", examples: ["Does it exist?", "Dinosaurs existed long ago"] },
        { title: "explain", base: "explain", past: "explained", participle: "explained", spanish: "explicar", examples: ["Explain the rule", "She explained clearly"] },
        { title: "fail", base: "fail", past: "failed", participle: "failed", spanish: "fallar", examples: ["Don't fail the test", "The plan failed"] },
        { title: "fill", base: "fill", past: "filled", participle: "filled", spanish: "llenar", examples: ["Fill the glass", "The room filled with smoke"] },
        { title: "finish", base: "finish", past: "finished", participle: "finished", spanish: "terminar", examples: ["Finish your work", "We finished early"] },
        { title: "follow", base: "follow", past: "followed", participle: "followed", spanish: "seguir", examples: ["Follow me", "The dog followed us"] },
        { title: "form", base: "form", past: "formed", participle: "formed", spanish: "formar", examples: ["Form a line", "Clouds formed in the sky"] },
        { title: "guess", base: "guess", past: "guessed", participle: "guessed", spanish: "adivinar", examples: ["Guess the answer", "I guessed correctly"] },
        { title: "happen", base: "happen", past: "happened", participle: "happened", spanish: "suceder", examples: ["What happened?", "The accident happened yesterday"] },
        { title: "help", base: "help", past: "helped", participle: "helped", spanish: "ayudar", examples: ["Help me please", "She helped her friend"] },
        { title: "hope", base: "hope", past: "hoped", participle: "hoped", spanish: "esperar", examples: ["I hope so", "We hoped for good weather"] },
        { title: "hurry", base: "hurry", past: "hurried", participle: "hurried", spanish: "apresurarse", examples: ["Hurry up!", "She hurried to work"] },
        { title: "include", base: "include", past: "included", participle: "included", spanish: "incluir", examples: ["Include everyone", "The price included tax"] },
        { title: "increase", base: "increase", past: "increased", participle: "increased", spanish: "aumentar", examples: ["Increase the volume", "Prices increased"] },
        { title: "invite", base: "invite", past: "invited", participle: "invited", spanish: "invitar", examples: ["Invite your friends", "She invited me to dinner"] },
        { title: "join", base: "join", past: "joined", participle: "joined", spanish: "unirse", examples: ["Join the club", "He joined the army"] },
        { title: "jump", base: "jump", past: "jumped", participle: "jumped", spanish: "saltar", examples: ["Jump high", "The cat jumped on the table"] },
        { title: "kill", base: "kill", past: "killed", participle: "killed", spanish: "matar", examples: ["Don't kill insects", "The frost killed the plants"] },
        { title: "knock", base: "knock", past: "knocked", participle: "knocked", spanish: "golpear", examples: ["Knock on the door", "Someone knocked loudly"] },
        { title: "land", base: "land", past: "landed", participle: "landed", spanish: "aterrizar", examples: ["The plane landed", "We landed safely"] },
        { title: "laugh", base: "laugh", past: "laughed", participle: "laughed", spanish: "reír", examples: ["She laughed at the joke", "We laughed together"] },
        { title: "learn", base: "learn", past: "learned", participle: "learned", spanish: "aprender", examples: ["I learn English", "He learned to drive"] },
        { title: "listen", base: "listen", past: "listened", participle: "listened", spanish: "escuchar", examples: ["Listen to music", "She listened carefully"] },
        { title: "live", base: "live", past: "lived", participle: "lived", spanish: "vivir", examples: ["I live here", "They lived in Paris"] },
        { title: "look", base: "look", past: "looked", participle: "looked", spanish: "mirar", examples: ["Look at me", "He looked tired"] },
        { title: "love", base: "love", past: "loved", participle: "loved", spanish: "amar", examples: ["I love you", "She loved the movie"] },
        { title: "manage", base: "manage", past: "managed", participle: "managed", spanish: "manejar", examples: ["Manage your time", "He managed the project"] },
        { title: "marry", base: "marry", past: "married", participle: "married", spanish: "casarse", examples: ["They marry next month", "She married him"] },
        { title: "match", base: "match", past: "matched", participle: "matched", spanish: "coincidir", examples: ["Colors match well", "The shoes matched"] },
        { title: "matter", base: "matter", past: "mattered", participle: "mattered", spanish: "importar", examples: ["It doesn't matter", "Your opinion mattered"] },
        { title: "measure", base: "measure", past: "measured", participle: "measured", spanish: "medir", examples: ["Measure the room", "He measured carefully"] },
        { title: "mention", base: "mention", past: "mentioned", participle: "mentioned", spanish: "mencionar", examples: ["Don't mention it", "She mentioned you"] },
        { title: "miss", base: "miss", past: "missed", participle: "missed", spanish: "extrañar", examples: ["I miss you", "He missed the bus"] },
        { title: "mix", base: "mix", past: "mixed", participle: "mixed", spanish: "mezclar", examples: ["Mix the ingredients", "She mixed the colors"] },
        { title: "need", base: "need", past: "needed", participle: "needed", spanish: "necesitar", examples: ["I need help", "We needed more time"] },
        { title: "notice", base: "notice", past: "noticed", participle: "noticed", spanish: "notar", examples: ["Notice the difference", "I noticed you"] },
        { title: "obtain", base: "obtain", past: "obtained", participle: "obtained", spanish: "obtener", examples: ["Obtain permission", "He obtained results"] },
        { title: "occur", base: "occur", past: "occurred", participle: "occurred", spanish: "ocurrir", examples: ["Accidents occur", "It occurred yesterday"] },
        { title: "offer", base: "offer", past: "offered", participle: "offered", spanish: "ofrecer", examples: ["I offer help", "She offered coffee"] },
        { title: "open", base: "open", past: "opened", participle: "opened", spanish: "abrir", examples: ["Open the door", "The store opened"] },
        { title: "order", base: "order", past: "ordered", participle: "ordered", spanish: "ordenar", examples: ["Order food", "He ordered pizza"] },
        { title: "organize", base: "organize", past: "organized", participle: "organized", spanish: "organizar", examples: ["Organize the event", "She organized well"] },
        { title: "paint", base: "paint", past: "painted", participle: "painted", spanish: "pintar", examples: ["Paint the wall", "He painted a picture"] },
        { title: "park", base: "park", past: "parked", participle: "parked", spanish: "estacionar", examples: ["Park the car", "She parked outside"] },
        { title: "pass", base: "pass", past: "passed", participle: "passed", spanish: "pasar", examples: ["Pass the test", "Time passed quickly"] },
        { title: "perform", base: "perform", past: "performed", participle: "performed", spanish: "realizar", examples: ["Perform well", "They performed music"] },
        { title: "pick", base: "pick", past: "picked", participle: "picked", spanish: "elegir", examples: ["Pick a color", "She picked flowers"] },
        { title: "plan", base: "plan", past: "planned", participle: "planned", spanish: "planear", examples: ["Plan the trip", "We planned ahead"] },
        { title: "plant", base: "plant", past: "planted", participle: "planted", spanish: "plantar", examples: ["Plant flowers", "He planted trees"] },
        { title: "point", base: "point", past: "pointed", participle: "pointed", spanish: "señalar", examples: ["Point to the map", "She pointed out"] },
        { title: "practice", base: "practice", past: "practiced", participle: "practiced", spanish: "practicar", examples: ["Practice English", "He practiced daily"] },
        { title: "prepare", base: "prepare", past: "prepared", participle: "prepared", spanish: "preparar", examples: ["Prepare dinner", "She prepared well"] },
        { title: "present", base: "present", past: "presented", participle: "presented", spanish: "presentar", examples: ["Present the project", "He presented ideas"] },
        { title: "produce", base: "produce", past: "produced", participle: "produced", spanish: "producir", examples: ["Produce results", "They produced goods"] },
        { title: "protect", base: "protect", past: "protected", participle: "protected", spanish: "proteger", examples: ["Protect yourself", "She protected him"] },
        { title: "provide", base: "provide", past: "provided", participle: "provided", spanish: "proporcionar", examples: ["Provide help", "He provided food"] },
        { title: "pull", base: "pull", past: "pulled", participle: "pulled", spanish: "tirar", examples: ["Pull the rope", "She pulled hard"] },
        { title: "push", base: "push", past: "pushed", participle: "pushed", spanish: "empujar", examples: ["Push the button", "He pushed the door"] },
        { title: "reach", base: "reach", past: "reached", participle: "reached", spanish: "alcanzar", examples: ["Reach the top", "She reached home"] },
        { title: "receive", base: "receive", past: "received", participle: "received", spanish: "recibir", examples: ["Receive a gift", "He received news"] },
        { title: "record", base: "record", past: "recorded", participle: "recorded", spanish: "grabar", examples: ["Record a video", "She recorded music"] },
        { title: "remain", base: "remain", past: "remained", participle: "remained", spanish: "permanecer", examples: ["Remain calm", "He remained quiet"] },
        { title: "remember", base: "remember", past: "remembered", participle: "remembered", spanish: "recordar", examples: ["Remember me", "She remembered well"] },
        { title: "remove", base: "remove", past: "removed", participle: "removed", spanish: "quitar", examples: ["Remove the stain", "He removed his hat"] },
        { title: "repair", base: "repair", past: "repaired", participle: "repaired", spanish: "reparar", examples: ["Repair the car", "She repaired it"] },
        { title: "repeat", base: "repeat", past: "repeated", participle: "repeated", spanish: "repetir", examples: ["Repeat the word", "He repeated twice"] },
        { title: "save", base: "save", past: "saved", participle: "saved", spanish: "ahorrar", examples: ["Save money", "He saved her life"] },
        { title: "search", base: "search", past: "searched", participle: "searched", spanish: "buscar", examples: ["Search online", "They searched everywhere"] },
        { title: "serve", base: "serve", past: "served", participle: "served", spanish: "servir", examples: ["Serve dinner", "She served customers"] },
        { title: "share", base: "share", past: "shared", participle: "shared", spanish: "compartir", examples: ["Share your food", "We shared stories"] },
        { title: "smile", base: "smile", past: "smiled", participle: "smiled", spanish: "sonreír", examples: ["Smile please", "She smiled warmly"] },
        { title: "study", base: "study", past: "studied", participle: "studied", spanish: "estudiar", examples: ["Study hard", "He studied medicine"] },
        { title: "travel", base: "travel", past: "traveled", participle: "traveled", spanish: "viajar", examples: ["Travel the world", "They traveled far"] }
    ];
}

function loadIrregularVerbs() {
    irregularVerbs = [
        { title: "be", base: "be", past: "was/were", participle: "been", spanish: "ser/estar", examples: ["I am happy", "She was tired yesterday"] },
        { title: "have", base: "have", past: "had", participle: "had", spanish: "tener", examples: ["I have a car", "He had lunch at noon"] },
        { title: "do", base: "do", past: "did", participle: "done", spanish: "hacer", examples: ["Do your homework", "She did it well"] },
        { title: "say", base: "say", past: "said", participle: "said", spanish: "decir", examples: ["Say hello", "He said goodbye"] },
        { title: "get", base: "get", past: "got", participle: "got/gotten", spanish: "obtener", examples: ["Get the book", "I got a present"] },
        { title: "make", base: "make", past: "made", participle: "made", spanish: "hacer", examples: ["Make dinner", "She made a cake"] },
        { title: "go", base: "go", past: "went", participle: "gone", spanish: "ir", examples: ["Go home", "They went to Paris"] },
        { title: "know", base: "know", past: "knew", participle: "known", spanish: "saber/conocer", examples: ["I know you", "She knew the answer"] },
        { title: "take", base: "take", past: "took", participle: "taken", spanish: "tomar", examples: ["Take this", "He took the bus"] },
        { title: "see", base: "see", past: "saw", participle: "seen", spanish: "ver", examples: ["See you later", "I saw a movie"] },
        { title: "come", base: "come", past: "came", participle: "come", spanish: "venir", examples: ["Come here", "She came early"] },
        { title: "think", base: "think", past: "thought", participle: "thought", spanish: "pensar", examples: ["Think about it", "I thought of you"] },
        { title: "look", base: "look", past: "looked", participle: "looked", spanish: "mirar", examples: ["Look at me", "She looked tired"] },
        { title: "want", base: "want", past: "wanted", participle: "wanted", spanish: "querer", examples: ["I want coffee", "He wanted to go"] },
        { title: "give", base: "give", past: "gave", participle: "given", spanish: "dar", examples: ["Give me that", "She gave a gift"] },
        { title: "use", base: "use", past: "used", participle: "used", spanish: "usar", examples: ["Use this pen", "He used the computer"] },
        { title: "find", base: "find", past: "found", participle: "found", spanish: "encontrar", examples: ["Find your keys", "I found it!"] },
        { title: "tell", base: "tell", past: "told", participle: "told", spanish: "decir/contar", examples: ["Tell me", "She told a story"] },
        { title: "work", base: "work", past: "worked", participle: "worked", spanish: "trabajar", examples: ["Work hard", "She worked late"] },
        { title: "seem", base: "seem", past: "seemed", participle: "seemed", spanish: "parecer", examples: ["You seem tired", "It seemed easy"] },
        { title: "feel", base: "feel", past: "felt", participle: "felt", spanish: "sentir", examples: ["Feel better", "I felt sad"] },
        { title: "try", base: "try", past: "tried", participle: "tried", spanish: "intentar", examples: ["Try again", "She tried hard"] },
        { title: "leave", base: "leave", past: "left", participle: "left", spanish: "dejar/salir", examples: ["Leave now", "He left early"] },
        { title: "call", base: "call", past: "called", participle: "called", spanish: "llamar", examples: ["Call me", "She called yesterday"] },
        { title: "put", base: "put", past: "put", participle: "put", spanish: "poner", examples: ["Put it here", "He put on his coat"] },
        { title: "mean", base: "mean", past: "meant", participle: "meant", spanish: "significar", examples: ["What does it mean?", "I meant to call"] },
        { title: "keep", base: "keep", past: "kept", participle: "kept", spanish: "mantener", examples: ["Keep quiet", "She kept the secret"] },
        { title: "let", base: "let", past: "let", participle: "let", spanish: "dejar/permitir", examples: ["Let me go", "They let us in"] },
        { title: "begin", base: "begin", past: "began", participle: "begun", spanish: "empezar", examples: ["Begin now", "The movie began"] },
        { title: "show", base: "show", past: "showed", participle: "shown", spanish: "mostrar", examples: ["Show me", "He showed the way"] },
        { title: "hear", base: "hear", past: "heard", participle: "heard", spanish: "oír", examples: ["Hear the music", "I heard a noise"] },
        { title: "play", base: "play", past: "played", participle: "played", spanish: "jugar", examples: ["Play football", "They played well"] },
        { title: "run", base: "run", past: "ran", participle: "run", spanish: "correr", examples: ["Run fast", "She ran home"] },
        { title: "move", base: "move", past: "moved", participle: "moved", spanish: "mover", examples: ["Move the chair", "We moved house"] },
        { title: "live", base: "live", past: "lived", participle: "lived", spanish: "vivir", examples: ["Live here", "He lived in Spain"] },
        { title: "bring", base: "bring", past: "brought", participle: "brought", spanish: "traer", examples: ["Bring your book", "He brought flowers"] },
        { title: "write", base: "write", past: "wrote", participle: "written", spanish: "escribir", examples: ["Write a letter", "She wrote a book"] },
        { title: "sit", base: "sit", past: "sat", participle: "sat", spanish: "sentarse", examples: ["Sit down", "He sat quietly"] },
        { title: "stand", base: "stand", past: "stood", participle: "stood", spanish: "estar de pie", examples: ["Stand up", "She stood by the door"] },
        { title: "lose", base: "lose", past: "lost", participle: "lost", spanish: "perder", examples: ["Don't lose it", "I lost my keys"] },
        { title: "pay", base: "pay", past: "paid", participle: "paid", spanish: "pagar", examples: ["Pay the bill", "She paid cash"] },
        { title: "meet", base: "meet", past: "met", participle: "met", spanish: "conocer/encontrar", examples: ["Meet me there", "We met yesterday"] },
        { title: "set", base: "set", past: "set", participle: "set", spanish: "poner/establecer", examples: ["Set the table", "He set a record"] },
        { title: "learn", base: "learn", past: "learned/learnt", participle: "learned/learnt", spanish: "aprender", examples: ["Learn English", "She learned quickly"] },
        { title: "break", base: "break", past: "broke", participle: "broken", spanish: "romper", examples: ["Don't break it", "He broke his arm"] },
        { title: "choose", base: "choose", past: "chose", participle: "chosen", spanish: "elegir", examples: ["Choose wisely", "She chose red"] },
        { title: "drive", base: "drive", past: "drove", participle: "driven", spanish: "conducir", examples: ["Drive carefully", "He drove home"] },
        { title: "eat", base: "eat", past: "ate", participle: "eaten", spanish: "comer", examples: ["Eat your food", "We ate dinner"] },
        { title: "fall", base: "fall", past: "fell", participle: "fallen", spanish: "caer", examples: ["Don't fall", "She fell down"] },
        { title: "forget", base: "forget", past: "forgot", participle: "forgotten", spanish: "olvidar", examples: ["Don't forget", "I forgot my keys"] },
        { title: "grow", base: "grow", past: "grew", participle: "grown", spanish: "crecer", examples: ["Plants grow", "He grew tall"] },
        { title: "hide", base: "hide", past: "hid", participle: "hidden", spanish: "esconder", examples: ["Hide the gift", "She hid behind"] },
        { title: "hold", base: "hold", past: "held", participle: "held", spanish: "sostener", examples: ["Hold my hand", "He held the baby"] },
        { title: "hurt", base: "hurt", past: "hurt", participle: "hurt", spanish: "lastimar", examples: ["Don't hurt me", "It hurt badly"] },
        { title: "lay", base: "lay", past: "laid", participle: "laid", spanish: "poner", examples: ["Lay the table", "She laid it down"] },
        { title: "lead", base: "lead", past: "led", participle: "led", spanish: "liderar", examples: ["Lead the way", "He led the team"] },
        { title: "lend", base: "lend", past: "lent", participle: "lent", spanish: "prestar", examples: ["Lend me money", "She lent her book"] },
        { title: "lie", base: "lie", past: "lay", participle: "lain", spanish: "acostarse", examples: ["Lie down", "He lay on the bed"] },
        { title: "ride", base: "ride", past: "rode", participle: "ridden", spanish: "montar", examples: ["Ride a bike", "She rode the horse"] },
        { title: "ring", base: "ring", past: "rang", participle: "rung", spanish: "sonar", examples: ["Ring the bell", "The phone rang"] },
        { title: "rise", base: "rise", past: "rose", participle: "risen", spanish: "levantarse", examples: ["Rise early", "The sun rose"] },
        { title: "sell", base: "sell", past: "sold", participle: "sold", spanish: "vender", examples: ["Sell the car", "He sold his house"] },
        { title: "send", base: "send", past: "sent", participle: "sent", spanish: "enviar", examples: ["Send a message", "She sent flowers"] },
        { title: "shine", base: "shine", past: "shone", participle: "shone", spanish: "brillar", examples: ["Stars shine", "The sun shone"] },
        { title: "shoot", base: "shoot", past: "shot", participle: "shot", spanish: "disparar", examples: ["Shoot the ball", "He shot the target"] },
        { title: "shut", base: "shut", past: "shut", participle: "shut", spanish: "cerrar", examples: ["Shut the door", "She shut her eyes"] },
        { title: "sing", base: "sing", past: "sang", participle: "sung", spanish: "cantar", examples: ["Sing a song", "They sang together"] },
        { title: "sink", base: "sink", past: "sank", participle: "sunk", spanish: "hundir", examples: ["Ships sink", "The boat sank"] },
        { title: "sleep", base: "sleep", past: "slept", participle: "slept", spanish: "dormir", examples: ["Sleep well", "He slept late"] },
        { title: "slide", base: "slide", past: "slid", participle: "slid", spanish: "deslizar", examples: ["Slide down", "She slid on ice"] },
        { title: "speak", base: "speak", past: "spoke", participle: "spoken", spanish: "hablar", examples: ["Speak English", "He spoke loudly"] },
        { title: "spend", base: "spend", past: "spent", participle: "spent", spanish: "gastar", examples: ["Spend money", "She spent time"] },
        { title: "split", base: "split", past: "split", participle: "split", spanish: "dividir", examples: ["Split the bill", "They split up"] },
        { title: "spread", base: "spread", past: "spread", participle: "spread", spanish: "extender", examples: ["Spread butter", "News spread fast"] },
        { title: "steal", base: "steal", past: "stole", participle: "stolen", spanish: "robar", examples: ["Don't steal", "Someone stole my bike"] },
        { title: "stick", base: "stick", past: "stuck", participle: "stuck", spanish: "pegar", examples: ["Stick the paper", "It stuck to the wall"] },
        { title: "strike", base: "strike", past: "struck", participle: "struck", spanish: "golpear", examples: ["Strike the ball", "Lightning struck"] },
        { title: "swear", base: "swear", past: "swore", participle: "sworn", spanish: "jurar", examples: ["Don't swear", "He swore to help"] },
        { title: "sweep", base: "sweep", past: "swept", participle: "swept", spanish: "barrer", examples: ["Sweep the floor", "She swept the leaves"] },
        { title: "swim", base: "swim", past: "swam", participle: "swum", spanish: "nadar", examples: ["Swim in the pool", "He swam across"] },
        { title: "swing", base: "swing", past: "swung", participle: "swung", spanish: "balancear", examples: ["Swing the bat", "She swung high"] },
        { title: "teach", base: "teach", past: "taught", participle: "taught", spanish: "enseñar", examples: ["Teach English", "He taught math"] },
        { title: "tear", base: "tear", past: "tore", participle: "torn", spanish: "rasgar", examples: ["Don't tear it", "She tore the paper"] },
        { title: "throw", base: "throw", past: "threw", participle: "thrown", spanish: "lanzar", examples: ["Throw the ball", "He threw it far"] },
        { title: "understand", base: "understand", past: "understood", participle: "understood", spanish: "entender", examples: ["I understand", "She understood well"] },
        { title: "wake", base: "wake", past: "woke", participle: "woken", spanish: "despertar", examples: ["Wake up early", "He woke at 6"] },
        { title: "wear", base: "wear", past: "wore", participle: "worn", spanish: "usar", examples: ["Wear a coat", "She wore red"] },
        { title: "win", base: "win", past: "won", participle: "won", spanish: "ganar", examples: ["Win the game", "They won first place"] },
        { title: "wind", base: "wind", past: "wound", participle: "wound", spanish: "enrollar", examples: ["Wind the clock", "She wound the rope"] },
        { title: "withdraw", base: "withdraw", past: "withdrew", participle: "withdrawn", spanish: "retirar", examples: ["Withdraw money", "He withdrew from the race"] },
        { title: "bite", base: "bite", past: "bit", participle: "bitten", spanish: "morder", examples: ["Don't bite", "The dog bit him"] },
        { title: "blow", base: "blow", past: "blew", participle: "blown", spanish: "soplar", examples: ["Blow the candle", "Wind blew hard"] },
        { title: "catch", base: "catch", past: "caught", participle: "caught", spanish: "atrapar", examples: ["Catch the ball", "She caught a cold"] },
        { title: "cut", base: "cut", past: "cut", participle: "cut", spanish: "cortar", examples: ["Cut the paper", "He cut his finger"] },
        { title: "dig", base: "dig", past: "dug", participle: "dug", spanish: "cavar", examples: ["Dig a hole", "They dug deep"] },
        { title: "draw", base: "draw", past: "drew", participle: "drawn", spanish: "dibujar", examples: ["Draw a picture", "She drew well"] },
        { title: "drink", base: "drink", past: "drank", participle: "drunk", spanish: "beber", examples: ["Drink water", "He drank coffee"] },
        { title: "feed", base: "feed", past: "fed", participle: "fed", spanish: "alimentar", examples: ["Feed the cat", "She fed the baby"] },
        { title: "fight", base: "fight", past: "fought", participle: "fought", spanish: "pelear", examples: ["Don't fight", "They fought bravely"] },
        { title: "fly", base: "fly", past: "flew", participle: "flown", spanish: "volar", examples: ["Birds fly", "We flew to Paris"] },
        { title: "light", base: "light", past: "lit", participle: "lit", spanish: "encender", examples: ["Light the fire", "He lit a candle"] },
        { title: "quit", base: "quit", past: "quit", participle: "quit", spanish: "renunciar", examples: ["Don't quit", "She quit her job"] },
        { title: "read", base: "read", past: "read", participle: "read", spanish: "leer", examples: ["Read books", "He read the news"] },
        { title: "seek", base: "seek", past: "sought", participle: "sought", spanish: "buscar", examples: ["Seek help", "They sought advice"] }
    ];
}
